.TH "git/FileKommander/src/com/poly/nlp/filekommander/gate Directory Reference" 3 "Thu Dec 20 2012" "Version 0.001" "FileKommander" \" -*- nroff -*-
.ad l
.nh
.SH NAME
git/FileKommander/src/com/poly/nlp/filekommander/gate Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBGateBuilder\&.java\fP"
.br
.ti -1c
.RI "file \fBProcessingResource\&.java\fP"
.br
.in -1c
