.TH "git/FileKommander/src/com/poly/nlp/filekommander/views/panels Directory Reference" 3 "Sat Dec 22 2012" "Version 0.001" "FileKommander" \" -*- nroff -*-
.ad l
.nh
.SH NAME
git/FileKommander/src/com/poly/nlp/filekommander/views/panels Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAbstractFileFolderPanel\&.java\fP"
.br
.ti -1c
.RI "file \fBAbstractMessagePanel\&.java\fP"
.br
.ti -1c
.RI "file \fBCreateActionPanel\&.java\fP"
.br
.ti -1c
.RI "file \fBDeleteActionPanel\&.java\fP"
.br
.ti -1c
.RI "file \fBEmptyActionPanel\&.java\fP"
.br
.ti -1c
.RI "file \fBExistActionPanel\&.java\fP"
.br
.ti -1c
.RI "file \fBGenericPanel\&.java\fP"
.br
.ti -1c
.RI "file \fBOpenActionPanel\&.java\fP"
.br
.ti -1c
.RI "file \fBPhraseOperationActionPanel\&.java\fP"
.br
.ti -1c
.RI "file \fBRenameActionPanel\&.java\fP"
.br
.ti -1c
.RI "file \fBStatsActionPanel\&.java\fP"
.br
.in -1c
