.TH "com.poly.nlp.filekommander.views.models" 3 "Thu Dec 20 2012" "Version 0.001" "FileKommander" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.poly.nlp.filekommander.views.models \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCreateModel\fP"
.br
.ti -1c
.RI "class \fBDeleteModel\fP"
.br
.ti -1c
.RI "interface \fBGenericActionModel\fP"
.br
.ti -1c
.RI "class \fBPhraseOperationModel\fP"
.br
.ti -1c
.RI "class \fBRenameModel\fP"
.br
.ti -1c
.RI "class \fBStatsModel\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FileKommander from the source code\&.
