.TH "com.poly.nlp.filekommander.views.panels.EmptyActionPanel" 3 "Thu Dec 20 2012" "Version 0.001" "FileKommander" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.poly.nlp.filekommander.views.panels.EmptyActionPanel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcom\&.poly\&.nlp\&.filekommander\&.views\&.panels\&.GenericPanel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEmptyActionPanel\fP ()"
.br
.ti -1c
.RI "void \fBupdatePanelData\fP (\fBGenericActionModel\fP actionModel)"
.br
.ti -1c
.RI "void \fBupdatePanelData\fP ()"
.br
.ti -1c
.RI "void \fBupdatePanelDataAfterAction\fP ()"
.br
.ti -1c
.RI "void \fBresetPanel\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final long \fBserialVersionUID\fP = 1L"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file EmptyActionPanel\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.poly\&.nlp\&.filekommander\&.views\&.panels\&.EmptyActionPanel\&.EmptyActionPanel ()"
Create the panel\&. 
.PP
Definition at line 12 of file EmptyActionPanel\&.java\&.
.PP
.nf
                              {
    }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void com\&.poly\&.nlp\&.filekommander\&.views\&.panels\&.EmptyActionPanel\&.resetPanel ()\fC [virtual]\fP"
Resets the panel to default state 
.PP
Implements \fBcom\&.poly\&.nlp\&.filekommander\&.views\&.panels\&.GenericPanel\fP\&.
.PP
Definition at line 28 of file EmptyActionPanel\&.java\&.
.PP
.nf
                             {
    }
.fi
.SS "void com\&.poly\&.nlp\&.filekommander\&.views\&.panels\&.EmptyActionPanel\&.updatePanelData (\fBGenericActionModel\fPactionModel)\fC [virtual]\fP"
Update the panel before action is taken using the given action model
.PP
\fBParameters:\fP
.RS 4
\fIactionModel\fP 
.RE
.PP

.PP
Implements \fBcom\&.poly\&.nlp\&.filekommander\&.views\&.panels\&.GenericPanel\fP\&.
.PP
Definition at line 16 of file EmptyActionPanel\&.java\&.
.PP
.nf
                                                                {
    }
.fi
.SS "void com\&.poly\&.nlp\&.filekommander\&.views\&.panels\&.EmptyActionPanel\&.updatePanelData ()\fC [virtual]\fP"
Update the panel before action is taken 
.PP
Implements \fBcom\&.poly\&.nlp\&.filekommander\&.views\&.panels\&.GenericPanel\fP\&.
.PP
Definition at line 20 of file EmptyActionPanel\&.java\&.
.PP
.nf
                                  {
    }
.fi
.SS "void com\&.poly\&.nlp\&.filekommander\&.views\&.panels\&.EmptyActionPanel\&.updatePanelDataAfterAction ()\fC [virtual]\fP"
updates the create panel after the action is run 
.PP
Implements \fBcom\&.poly\&.nlp\&.filekommander\&.views\&.panels\&.GenericPanel\fP\&.
.PP
Definition at line 24 of file EmptyActionPanel\&.java\&.
.PP
.nf
                                             {
    }
.fi
.SH "Member Data Documentation"
.PP 
.SS "final long com\&.poly\&.nlp\&.filekommander\&.views\&.panels\&.EmptyActionPanel\&.serialVersionUID = 1L\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 7 of file EmptyActionPanel\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FileKommander from the source code\&.
