.TH "com.poly.nlp" 3 "Thu Dec 20 2012" "Version 0.001" "FileKommander" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.poly.nlp \- 
.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBfilekommander\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FileKommander from the source code\&.
