.TH "com.poly.nlp.filekommander.views.models.PhraseOperationModel" 3 "Thu Dec 20 2012" "Version 0.001" "FileKommander" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.poly.nlp.filekommander.views.models.PhraseOperationModel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcom\&.poly\&.nlp\&.filekommander\&.views\&.models\&.GenericActionModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPhraseOperationModel\fP ()"
.br
.ti -1c
.RI "void \fBadd\fP (String name)"
.br
.ti -1c
.RI "HashMap< String, String > \fBgetFileListData\fP ()"
.br
.ti -1c
.RI "void \fBsetFileListData\fP (HashMap< String, String > \fBfileListData\fP)"
.br
.ti -1c
.RI "int \fBgetOperationType\fP ()"
.br
.ti -1c
.RI "void \fBsetOperationType\fP (int \fBoperationType\fP)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "HashMap< String, String > \fBfileListData\fP"
.br
.ti -1c
.RI "int \fBoperationType\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file PhraseOperationModel\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\&.PhraseOperationModel ()"

.PP
Definition at line 10 of file PhraseOperationModel\&.java\&.
.PP
.nf
                                 {
        this\&.fileListData = new HashMap<String, String>() ;
    }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void com\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\&.add (Stringname)"

.PP
Definition at line 14 of file PhraseOperationModel\&.java\&.
.PP
.nf
                                 {
        this\&.fileListData\&.put(name, '');  
    }
.fi
.SS "HashMap<String, String> com\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\&.getFileListData ()"
\fBReturns:\fP
.RS 4
the fileListData 
.RE
.PP

.PP
Definition at line 21 of file PhraseOperationModel\&.java\&.
.PP
.nf
                                                     {
        return fileListData;
    }
.fi
.SS "int com\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\&.getOperationType ()"

.PP
Definition at line 32 of file PhraseOperationModel\&.java\&.
.PP
.nf
                                  {
        return operationType;
    }
.fi
.SS "void com\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\&.setFileListData (HashMap< String, String >fileListData)"
\fBParameters:\fP
.RS 4
\fIfileListData\fP the fileListData to set 
.RE
.PP

.PP
Definition at line 28 of file PhraseOperationModel\&.java\&.
.PP
.nf
                                                                      {
        this\&.fileListData = fileListData;
    }
.fi
.SS "void com\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\&.setOperationType (intoperationType)"

.PP
Definition at line 36 of file PhraseOperationModel\&.java\&.
.PP
.nf
                                                    {
        this\&.operationType = operationType;
    }
.fi
.SH "Member Data Documentation"
.PP 
.SS "HashMap<String, String> com\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\&.fileListData\fC [private]\fP"

.PP
Definition at line 7 of file PhraseOperationModel\&.java\&.
.SS "int com\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\&.operationType\fC [private]\fP"

.PP
Definition at line 8 of file PhraseOperationModel\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FileKommander from the source code\&.
