.TH "com.poly.nlp.filekommander.file.actions.CallAction" 3 "Sat Dec 22 2012" "Version 0.001" "FileKommander" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.poly.nlp.filekommander.file.actions.CallAction \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBGenericActionModel\fP \fBcallAction\fP (\fBGenericActionModel\fP actionModel)"
.br
.ti -1c
.RI "static \fBPhraseOperationModel\fP \fBinsertAction\fP (\fBPhraseOperationModel\fP phraseModel)"
.br
.ti -1c
.RI "static \fBOpenModel\fP \fBopenAction\fP (\fBOpenModel\fP openModel)"
.br
.ti -1c
.RI "static \fBPhraseOperationModel\fP \fBremoveAction\fP (\fBPhraseOperationModel\fP phraseModel)"
.br
.ti -1c
.RI "static \fBPhraseOperationModel\fP \fBreplaceAction\fP (\fBPhraseOperationModel\fP phraseModel)"
.br
.ti -1c
.RI "static \fBGenericActionModel\fP \fBstatsAction\fP (\fBStatsModel\fP statsModel)"
.br
.ti -1c
.RI "static \fBGenericActionModel\fP \fBphraseAction\fP (\fBPhraseOperationModel\fP phraseModel)"
.br
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static \fBGenericActionModel\fP \fBcreateAction\fP (\fBCreateModel\fP createModel)"
.br
.ti -1c
.RI "static \fBDeleteModel\fP \fBdeleteAction\fP (\fBDeleteModel\fP deleteModel)"
.br
.ti -1c
.RI "static \fBExistsModel\fP \fBexistsAction\fP (\fBExistsModel\fP existsModel)"
.br
.ti -1c
.RI "static \fBGenericActionModel\fP \fBrenameAction\fP (\fBRenameModel\fP renameModel)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final Logger \fBlog\fP = Logger\&.getLogger(CallAction\&.class)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file CallAction\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBGenericActionModel\fP com\&.poly\&.nlp\&.filekommander\&.file\&.actions\&.CallAction\&.callAction (\fBGenericActionModel\fPactionModel)\fC [static]\fP"

.PP
Definition at line 27 of file CallAction\&.java\&.
.PP
.nf
                                                                                {
        log\&.info('Checking which action to call in callAction function ');
        GenericActionModel newActionModel = null;
        if (actionModel == null)
            return null;

        if (actionModel instanceof CreateModel) {
            newActionModel = createAction((CreateModel) actionModel);
        } else if (actionModel instanceof DeleteModel) {
            newActionModel =    deleteAction((DeleteModel) actionModel);
        }  else if (actionModel instanceof RenameModel) {
            newActionModel =    renameAction((RenameModel) actionModel);
        }else if(actionModel instanceof StatsModel){
            newActionModel =    statsAction((StatsModel) actionModel);
        }else if(actionModel instanceof ExistsModel){
            newActionModel =    existsAction((ExistsModel) actionModel);
        }else if(actionModel instanceof OpenModel){
            newActionModel =    openAction((OpenModel) actionModel);
        }else if(actionModel instanceof PhraseOperationModel){
            newActionModel =    phraseAction((PhraseOperationModel) actionModel);
        }else {
            //existsAction();
    //      insertAction();
        //  openAction();
        //  removeAction();
        // renameAction();
        //  replaceAction();
        //  statsAction();

        }
        return newActionModel;
    }
.fi
.SS "static \fBGenericActionModel\fP com\&.poly\&.nlp\&.filekommander\&.file\&.actions\&.CallAction\&.createAction (\fBCreateModel\fPcreateModel)\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 60 of file CallAction\&.java\&.
.PP
.nf
                                                                            {
        log\&.info('CreateAction action called for model' + createModel);
        HashMap<String, String> fileListData = createModel\&.getFileListData();
        HashMap<String, String> folderListData = createModel
                \&.getFolderListData();

        for (String fileName : fileListData\&.keySet()) {
            String message = FileActionUtils\&.createFile(fileName);
            fileListData\&.put(fileName, message);
        }
        for (String folderName : folderListData\&.keySet()) {
            String message = FileActionUtils\&.createFolder(folderName);
            folderListData\&.put(folderName, message);
        }
        createModel\&.setModelRun(true);
        createModel\&.setFileListData(fileListData);
        createModel\&.setFolderListData(folderListData);
        return createModel;
    }
.fi
.SS "static \fBDeleteModel\fP com\&.poly\&.nlp\&.filekommander\&.file\&.actions\&.CallAction\&.deleteAction (\fBDeleteModel\fPdeleteModel)\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 80 of file CallAction\&.java\&.
.PP
.nf
                                                                     {
        log\&.info('DeleteAction action called for model' + deleteModel);
        HashMap<String, String> fileListData = deleteModel\&.getFileListData();
        HashMap<String, String> folderListData = deleteModel
                \&.getFolderListData();

        for (String fileName : fileListData\&.keySet()) {
            String message = FileActionUtils\&.deleteFile(fileName);
            fileListData\&.put(fileName, message);
        }
        for (String folderName : folderListData\&.keySet()) {
            String message = FileActionUtils\&.deleteFolder(folderName);
            folderListData\&.put(folderName, message);
        }
        deleteModel\&.setModelRun(true);
        deleteModel\&.setFileListData(fileListData);
        deleteModel\&.setFolderListData(folderListData);
        return deleteModel  ;
    }
.fi
.SS "static \fBExistsModel\fP com\&.poly\&.nlp\&.filekommander\&.file\&.actions\&.CallAction\&.existsAction (\fBExistsModel\fPexistsModel)\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 100 of file CallAction\&.java\&.
.PP
.nf
                                                                     {
        log\&.info('ExistsAction action called');

        HashMap<String, String> fileListData = existsModel\&.getFileListData();
        HashMap<String, String> folderListData = existsModel\&.getFolderListData();
        
        Set<String> keySet = fileListData\&.keySet();
        for (String fileName : keySet) {
            String message = FileActionUtils\&.exists(fileName);
            fileListData\&.put(fileName, message);
        }
        keySet = folderListData\&.keySet();
        for (String folderName : keySet) {
            String message = FileActionUtils\&.exists(folderName);
            fileListData\&.put(folderName, message);
        }
        existsModel\&.setFileListData(fileListData);
        existsModel\&.setFolderListData(folderListData);
        existsModel\&.setModelRun(true);
        return existsModel;
    }
.fi
.SS "static \fBPhraseOperationModel\fP com\&.poly\&.nlp\&.filekommander\&.file\&.actions\&.CallAction\&.insertAction (\fBPhraseOperationModel\fPphraseModel)\fC [static]\fP"

.PP
Definition at line 122 of file CallAction\&.java\&.
.PP
.nf
                                                                                      {
        log\&.info('InsertAction action called');
        String oldPhrase = phraseModel\&.getOldPhrase();
        String newPhrase = phraseModel\&.getNewPhrase();
        String position = phraseModel\&.getPosition() ;
        String repetition = phraseModel\&.getRepetition();
        HashMap<String, String> fileListData = phraseModel\&.getFileListData();
        
        Set<String> keySet = fileListData\&.keySet();
        for (String fileName : keySet) {
        String message = FileActionUtils\&.insert(newPhrase, oldPhrase, position, repetition, fileName) ;  
        fileListData\&.put(fileName, message);
        }
        
        return phraseModel;
    }
.fi
.SS "static \fBOpenModel\fP com\&.poly\&.nlp\&.filekommander\&.file\&.actions\&.CallAction\&.openAction (\fBOpenModel\fPopenModel)\fC [static]\fP"

.PP
Definition at line 139 of file CallAction\&.java\&.
.PP
.nf
                                                            {
        log\&.info('ExistsAction action called');

        HashMap<String, String> fileListData = openModel\&.getFileListData();
        HashMap<String, String> folderListData = openModel\&.getFolderListData();
        
        Set<String> keySet = fileListData\&.keySet();
        for (String fileName : keySet) {
            String message = FileActionUtils\&.open(fileName);
            fileListData\&.put(fileName, message);
        }
        keySet = folderListData\&.keySet();
        for (String folderName : keySet) {
            String message = FileActionUtils\&.open(folderName);
            fileListData\&.put(folderName, message);
        }
        openModel\&.setFileListData(fileListData);
        openModel\&.setFolderListData(folderListData);
        openModel\&.setModelRun(true);
        return openModel;
    }
.fi
.SS "static \fBGenericActionModel\fP com\&.poly\&.nlp\&.filekommander\&.file\&.actions\&.CallAction\&.phraseAction (\fBPhraseOperationModel\fPphraseModel)\fC [static]\fP"

.PP
Definition at line 250 of file CallAction\&.java\&.
.PP
.nf
                                                                                    {
        log\&.info('PhraseAction action called');

        int action = phraseModel\&.getOperationType() ;
        String oldPhrase = phraseModel\&.getOldPhrase();
        String newPhrase = phraseModel\&.getNewPhrase();
        String position = phraseModel\&.getPosition();
        String repetition = phraseModel\&.getRepetition();
        HashMap<String, String> fileListData = phraseModel\&.getFileListData();
        
        Set<String> keySet = fileListData\&.keySet();
//      for (String fileName : keySet) {
//      String message = FileActionUtils\&.insert(newPhrase, oldPhrase, position, repetition, fileName) ;  
//      fileListData\&.put(fileName, message);
//      }
//      
        switch (action) {
        case 7:
            phraseModel = insertAction(phraseModel);
            break;
        case 8:
            phraseModel = replaceAction(phraseModel);
            break;
        case 9:
            phraseModel = removeAction(phraseModel);
            break;
        default:
            break;
        }
        return phraseModel;     
    }
.fi
.SS "static \fBPhraseOperationModel\fP com\&.poly\&.nlp\&.filekommander\&.file\&.actions\&.CallAction\&.removeAction (\fBPhraseOperationModel\fPphraseModel)\fC [static]\fP"

.PP
Definition at line 161 of file CallAction\&.java\&.
.PP
.nf
                                                                                      {
        log\&.info('RemoveAction action called');
        String oldPhrase = phraseModel\&.getOldPhrase();
        String newPhrase = phraseModel\&.getNewPhrase();
        String position = phraseModel\&.getPosition() ;
        String repetition = phraseModel\&.getRepetition();
        HashMap<String, String> fileListData = phraseModel\&.getFileListData();
        
        Set<String> keySet = fileListData\&.keySet();
        for (String fileName : keySet) {
        String message = FileActionUtils\&.remove(oldPhrase, repetition, fileName) ;   
        fileListData\&.put(fileName, message);
        }
        
        return phraseModel;
    }
.fi
.SS "static \fBGenericActionModel\fP com\&.poly\&.nlp\&.filekommander\&.file\&.actions\&.CallAction\&.renameAction (\fBRenameModel\fPrenameModel)\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 178 of file CallAction\&.java\&.
.PP
.nf
                                                                            {
        log\&.info('RenameAction action called');
        String oldFileName = renameModel\&.getOldFileName();
        String newFileName = renameModel\&.getNewFileName();
       String message = FileActionUtils\&.rename(oldFileName, newFileName);
        renameModel\&.setErrorMessage(message);
        renameModel\&.setModelRun(true);
        return renameModel;
    }
.fi
.SS "static \fBPhraseOperationModel\fP com\&.poly\&.nlp\&.filekommander\&.file\&.actions\&.CallAction\&.replaceAction (\fBPhraseOperationModel\fPphraseModel)\fC [static]\fP"

.PP
Definition at line 188 of file CallAction\&.java\&.
.PP
.nf
                                                                                       {
        log\&.info('ReplaceAction action called');
        String oldPhrase = phraseModel\&.getOldPhrase();
        String newPhrase = phraseModel\&.getNewPhrase();
        String position = phraseModel\&.getPosition() ;
        String repetition = phraseModel\&.getRepetition();
        HashMap<String, String> fileListData = phraseModel\&.getFileListData();
        
        Set<String> keySet = fileListData\&.keySet();
        for (String fileName : keySet) {
            String message = FileActionUtils\&.replace(newPhrase, oldPhrase, repetition, fileName);
        //String message = FileActionUtils\&.replace(newPhrase, oldPhrase, position, repetition, fileName) ;   
        fileListData\&.put(fileName, message);
        }
        
        return phraseModel;
    }
.fi
.SS "static \fBGenericActionModel\fP com\&.poly\&.nlp\&.filekommander\&.file\&.actions\&.CallAction\&.statsAction (\fBStatsModel\fPstatsModel)\fC [static]\fP"

.PP
Definition at line 206 of file CallAction\&.java\&.
.PP
.nf
                                                                        {
        log\&.info('StatsAction action called'); 
        //iterate over every file/folder and find the stats type and call the corr\&. function 
        HashMap<String, String> fileListData = statsModel\&.getFileListData();
        HashMap<String, String> folderListData = statsModel\&.getFolderListData();

        for (String fileName : fileListData\&.keySet()) {
            if(statsModel\&.getStatsType() == FileKommander\&.COUNT){
                int count = FileActionUtils\&.countWords(fileName);
                String message = 'Count of all the words is '+count +' ';
                fileListData\&.put(fileName, message);
            }else if(statsModel\&.getStatsType() == FileKommander\&.COUNT_WORD){
        //      int count = countSpecificWord(fileName, word); //where is dis word passed from ?? how??
        //      String message = 'The word '+word+' appears '+count+' times';
        //      fileListData\&.put(fileName, message);
            } else if(statsModel\&.getStatsType() == FileKommander\&.LAST_MODIFIED){
                String message = FileActionUtils\&.lastModified(fileName);
                fileListData\&.put(fileName, message);
            } else if(statsModel\&.getStatsType() == FileKommander\&.SIZEOF){
                String message = FileActionUtils\&.sizeOf(fileName);
                fileListData\&.put(fileName, message);
            }
        }
        for (String folderName : folderListData\&.keySet()) {
            if(statsModel\&.getStatsType() == FileKommander\&.COUNT){
                int count = FileActionUtils\&.countFiles(folderName);
                String message = 'Count of all the files in the folder '+folderName+' is '+count;
                fileListData\&.put(folderName, message);
            } else if(statsModel\&.getStatsType() == FileKommander\&.LIST_FILES){
                ArrayList<String> l = new ArrayList<String>();
                ArrayList<String> list = FileActionUtils\&.listFiles(folderName, l);
            
                folderListData\&.put(folderName, 'List of files :' + list\&.toString());
            } else if(statsModel\&.getStatsType() == FileKommander\&.SIZEOF){
                String message = FileActionUtils\&.sizeOf(folderName);
                folderListData\&.put(folderName, message);
            }
        }
        statsModel\&.setModelRun(true);
        statsModel\&.setFileListData(fileListData);
        statsModel\&.setFolderListData(folderListData);
        return statsModel;
    }
.fi
.SH "Member Data Documentation"
.PP 
.SS "final Logger com\&.poly\&.nlp\&.filekommander\&.file\&.actions\&.CallAction\&.log = Logger\&.getLogger(CallAction\&.class)\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 25 of file CallAction\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FileKommander from the source code\&.
