.TH "com.poly.nlp.filekommander.file.actions.OSDetector" 3 "Sat Dec 22 2012" "Version 0.001" "FileKommander" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.poly.nlp.filekommander.file.actions.OSDetector \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static boolean \fBisWindows\fP ()"
.br
.ti -1c
.RI "static boolean \fBisLinux\fP ()"
.br
.ti -1c
.RI "static boolean \fBisMac\fP ()"
.br
.in -1c
.SS "Static Package Functions"

.in +1c
.ti -1c
.RI "\fB[static initializer]\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static boolean \fBisWindows\fP = false"
.br
.ti -1c
.RI "static boolean \fBisLinux\fP = false"
.br
.ti -1c
.RI "static boolean \fBisMac\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file OSDetector\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "com\&.poly\&.nlp\&.filekommander\&.file\&.actions\&.OSDetector\&.[static initializer] ()\fC [static]\fP, \fC [package]\fP"

.SS "static boolean com\&.poly\&.nlp\&.filekommander\&.file\&.actions\&.OSDetector\&.isLinux ()\fC [static]\fP"

.PP
Definition at line 19 of file OSDetector\&.java\&.
.PP
.nf
                                    {
        return isLinux;
    }
.fi
.SS "static boolean com\&.poly\&.nlp\&.filekommander\&.file\&.actions\&.OSDetector\&.isMac ()\fC [static]\fP"

.PP
Definition at line 23 of file OSDetector\&.java\&.
.PP
.nf
                                  {
        return isMac;
    }
.fi
.SS "static boolean com\&.poly\&.nlp\&.filekommander\&.file\&.actions\&.OSDetector\&.isWindows ()\fC [static]\fP"

.PP
Definition at line 15 of file OSDetector\&.java\&.
.PP
.nf
                                      {
        return isWindows;
    }
.fi
.SH "Member Data Documentation"
.PP 
.SS "boolean com\&.poly\&.nlp\&.filekommander\&.file\&.actions\&.OSDetector\&.isLinux = false\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 5 of file OSDetector\&.java\&.
.SS "boolean com\&.poly\&.nlp\&.filekommander\&.file\&.actions\&.OSDetector\&.isMac = false\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 6 of file OSDetector\&.java\&.
.SS "boolean com\&.poly\&.nlp\&.filekommander\&.file\&.actions\&.OSDetector\&.isWindows = false\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 4 of file OSDetector\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FileKommander from the source code\&.
