.TH "com.poly.nlp.filekommander.views.panels" 3 "Sat Dec 22 2012" "Version 0.001" "FileKommander" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.poly.nlp.filekommander.views.panels \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbstractFileFolderPanel\fP"
.br
.ti -1c
.RI "class \fBAbstractMessagePanel\fP"
.br
.ti -1c
.RI "class \fBCreateActionPanel\fP"
.br
.ti -1c
.RI "class \fBDeleteActionPanel\fP"
.br
.ti -1c
.RI "class \fBEmptyActionPanel\fP"
.br
.ti -1c
.RI "class \fBExistActionPanel\fP"
.br
.ti -1c
.RI "class \fBGenericPanel\fP"
.br
.ti -1c
.RI "class \fBOpenActionPanel\fP"
.br
.ti -1c
.RI "class \fBPhraseOperationActionPanel\fP"
.br
.ti -1c
.RI "class \fBRenameActionPanel\fP"
.br
.ti -1c
.RI "class \fBStatsActionPanel\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FileKommander from the source code\&.
