.TH "com.poly.nlp.filekommander.views.models.PhraseOperationModel" 3 "Sat Dec 22 2012" "Version 0.001" "FileKommander" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.poly.nlp.filekommander.views.models.PhraseOperationModel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcom\&.poly\&.nlp\&.filekommander\&.views\&.models\&.GenericActionModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPhraseOperationModel\fP ()"
.br
.ti -1c
.RI "void \fBadd\fP (String name)"
.br
.ti -1c
.RI "HashMap< String, String > \fBgetFileListData\fP ()"
.br
.ti -1c
.RI "void \fBsetFileListData\fP (HashMap< String, String > \fBfileListData\fP)"
.br
.ti -1c
.RI "int \fBgetOperationType\fP ()"
.br
.ti -1c
.RI "void \fBsetOperationType\fP (int \fBoperationType\fP)"
.br
.ti -1c
.RI "String \fBgetNewPhrase\fP ()"
.br
.ti -1c
.RI "void \fBsetNewPhrase\fP (String \fBnewPhrase\fP)"
.br
.ti -1c
.RI "String \fBgetOldPhrase\fP ()"
.br
.ti -1c
.RI "void \fBsetOldPhrase\fP (String \fBoldPhrase\fP)"
.br
.ti -1c
.RI "String \fBgetRepetition\fP ()"
.br
.ti -1c
.RI "void \fBsetRepetition\fP (String \fBrepetition\fP)"
.br
.ti -1c
.RI "String \fBgetPosition\fP ()"
.br
.ti -1c
.RI "void \fBsetPosition\fP (String \fBposition\fP)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "HashMap< String, String > \fBfileListData\fP"
.br
.ti -1c
.RI "int \fBoperationType\fP"
.br
.ti -1c
.RI "String \fBrepetition\fP"
.br
.ti -1c
.RI "String \fBposition\fP"
.br
.ti -1c
.RI "String \fBnewPhrase\fP"
.br
.ti -1c
.RI "String \fBoldPhrase\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file PhraseOperationModel\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\&.PhraseOperationModel ()"

.PP
Definition at line 27 of file PhraseOperationModel\&.java\&.
.PP
.nf
                                 {
        this\&.fileListData = new HashMap<String, String>() ;
        newPhrase = '';
        oldPhrase = '';
    }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void com\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\&.add (Stringname)"

.PP
Definition at line 33 of file PhraseOperationModel\&.java\&.
.PP
.nf
                                 {
        this\&.fileListData\&.put(name, '');  
    }
.fi
.SS "HashMap<String, String> com\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\&.getFileListData ()"
\fBReturns:\fP
.RS 4
the fileListData 
.RE
.PP

.PP
Definition at line 40 of file PhraseOperationModel\&.java\&.
.PP
.nf
                                                     {
        return fileListData;
    }
.fi
.SS "String com\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\&.getNewPhrase ()"
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 68 of file PhraseOperationModel\&.java\&.
.PP
.nf
                                 {
        return newPhrase;
    }
.fi
.SS "String com\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\&.getOldPhrase ()"
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 82 of file PhraseOperationModel\&.java\&.
.PP
.nf
                                 {
        return oldPhrase;
    }
.fi
.SS "int com\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\&.getOperationType ()"
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 54 of file PhraseOperationModel\&.java\&.
.PP
.nf
                                  {
        return operationType;
    }
.fi
.SS "String com\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\&.getPosition ()"
\fBReturns:\fP
.RS 4
the position 
.RE
.PP

.PP
Definition at line 110 of file PhraseOperationModel\&.java\&.
.PP
.nf
                                {
        return position;
    }
.fi
.SS "String com\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\&.getRepetition ()"
\fBReturns:\fP
.RS 4
the repetition 
.RE
.PP

.PP
Definition at line 96 of file PhraseOperationModel\&.java\&.
.PP
.nf
                                  {
        return repetition;
    }
.fi
.SS "void com\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\&.setFileListData (HashMap< String, String >fileListData)"
\fBParameters:\fP
.RS 4
\fIfileListData\fP the fileListData to set 
.RE
.PP

.PP
Definition at line 47 of file PhraseOperationModel\&.java\&.
.PP
.nf
                                                                      {
        this\&.fileListData = fileListData;
    }
.fi
.SS "void com\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\&.setNewPhrase (StringnewPhrase)"
\fBParameters:\fP
.RS 4
\fInewPhrase\fP 
.RE
.PP

.PP
Definition at line 75 of file PhraseOperationModel\&.java\&.
.PP
.nf
                                               {
        this\&.newPhrase = newPhrase;
    }
.fi
.SS "void com\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\&.setOldPhrase (StringoldPhrase)"
\fBParameters:\fP
.RS 4
\fIoldPhrase\fP 
.RE
.PP

.PP
Definition at line 89 of file PhraseOperationModel\&.java\&.
.PP
.nf
                                               {
        this\&.oldPhrase = oldPhrase;
    }
.fi
.SS "void com\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\&.setOperationType (intoperationType)"
\fBParameters:\fP
.RS 4
\fIoperationType\fP 
.RE
.PP

.PP
Definition at line 61 of file PhraseOperationModel\&.java\&.
.PP
.nf
                                                    {
        this\&.operationType = operationType;
    }
.fi
.SS "void com\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\&.setPosition (Stringposition)"
\fBParameters:\fP
.RS 4
\fIposition\fP the position to set 
.RE
.PP

.PP
Definition at line 117 of file PhraseOperationModel\&.java\&.
.PP
.nf
                                             {
        this\&.position = position;
    }
.fi
.SS "void com\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\&.setRepetition (Stringrepetition)"
\fBParameters:\fP
.RS 4
\fIrepetition\fP the repetition to set 
.RE
.PP

.PP
Definition at line 103 of file PhraseOperationModel\&.java\&.
.PP
.nf
                                                 {
        this\&.repetition = repetition;
    }
.fi
.SH "Member Data Documentation"
.PP 
.SS "HashMap<String, String> com\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\&.fileListData\fC [private]\fP"

.PP
Definition at line 9 of file PhraseOperationModel\&.java\&.
.SS "String com\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\&.newPhrase\fC [private]\fP"

.PP
Definition at line 22 of file PhraseOperationModel\&.java\&.
.SS "String com\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\&.oldPhrase\fC [private]\fP"

.PP
Definition at line 25 of file PhraseOperationModel\&.java\&.
.SS "int com\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\&.operationType\fC [private]\fP"

.PP
Definition at line 12 of file PhraseOperationModel\&.java\&.
.SS "String com\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\&.position\fC [private]\fP"

.PP
Definition at line 18 of file PhraseOperationModel\&.java\&.
.SS "String com\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\&.repetition\fC [private]\fP"

.PP
Definition at line 15 of file PhraseOperationModel\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FileKommander from the source code\&.
