.TH "com.poly.nlp.filekommander.views.panels.PhraseOperationActionPanel" 3 "Sat Dec 22 2012" "Version 0.001" "FileKommander" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.poly.nlp.filekommander.views.panels.PhraseOperationActionPanel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcom\&.poly\&.nlp\&.filekommander\&.views\&.panels\&.AbstractMessagePanel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPhraseOperationActionPanel\fP ()"
.br
.ti -1c
.RI "void \fBupdatePanelData\fP (\fBGenericActionModel\fP \fBmodel\fP)"
.br
.ti -1c
.RI "void \fBupdatePanelData\fP ()"
.br
.ti -1c
.RI "void \fBupdatePanelDataAfterAction\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBPhraseOperationModel\fP \fBmodel\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final long \fBserialVersionUID\fP = 1L"
.br
.ti -1c
.RI "static final Logger \fBlog\fP = Logger\&.getLogger(PhraseOperationActionPanel\&.class)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 26 of file PhraseOperationActionPanel\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.poly\&.nlp\&.filekommander\&.views\&.panels\&.PhraseOperationActionPanel\&.PhraseOperationActionPanel ()"
Create the panel\&. 
.PP
Definition at line 37 of file PhraseOperationActionPanel\&.java\&.
.PP
.nf
                                        {
        super();
    }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void com\&.poly\&.nlp\&.filekommander\&.views\&.panels\&.PhraseOperationActionPanel\&.updatePanelData (\fBGenericActionModel\fPactionModel)\fC [virtual]\fP"
Update the panel before action is taken using the given action model
.PP
\fBParameters:\fP
.RS 4
\fIactionModel\fP 
.RE
.PP

.PP
Implements \fBcom\&.poly\&.nlp\&.filekommander\&.views\&.panels\&.AbstractMessagePanel\fP\&.
.PP
Definition at line 41 of file PhraseOperationActionPanel\&.java\&.
.PP
.nf
                                                          {
        if(model instanceof PhraseOperationModel){
        this\&.model = (PhraseOperationModel)model;    
        updatePanelData();
        }else{
            log\&.error('Wrong class');
        }
    }
.fi
.SS "void com\&.poly\&.nlp\&.filekommander\&.views\&.panels\&.PhraseOperationActionPanel\&.updatePanelData ()\fC [virtual]\fP"
Update the panel before action is taken 
.PP
Implements \fBcom\&.poly\&.nlp\&.filekommander\&.views\&.panels\&.AbstractMessagePanel\fP\&.
.PP
Definition at line 50 of file PhraseOperationActionPanel\&.java\&.
.PP
.nf
                                  {
        getMessagePanel()\&.removeAll();
        model = (PhraseOperationModel) CallAction\&.callAction(model);
        HashMap<String, String> fileListData = this\&.model\&.getFileListData();
        
        if (fileListData\&.size() > 1) {
            setActionString('The details for the following files/folders will be shown');
        } else if (fileListData\&.size() == 0) {
            setActionString('');
        } else {
            setActionString('The details for the following file/folder will be shown');
        }
        
        Set<String> keySet = fileListData\&.keySet();
        Iterator<String> iterator = keySet\&.iterator();
        
        while(iterator\&.hasNext())
        {   
            String key = iterator\&.next();
            String value= fileListData\&.get(key);
            
            String [] data = new String[2];
            data[0] = key;
            data[1]= value;
            getMessagePanel()\&.add(createDefaultMessageRow(data));
        }
        getMessagePanel()\&.setVisible(true);
        this\&.paintAll(this\&.getGraphics());        

    }
.fi
.SS "void com\&.poly\&.nlp\&.filekommander\&.views\&.panels\&.PhraseOperationActionPanel\&.updatePanelDataAfterAction ()\fC [virtual]\fP"
updates the create panel after the action is run 
.PP
Implements \fBcom\&.poly\&.nlp\&.filekommander\&.views\&.panels\&.AbstractMessagePanel\fP\&.
.PP
Definition at line 90 of file PhraseOperationActionPanel\&.java\&.
.PP
.nf
                                             {
        // TODO Auto-generated method stub
        
    }
.fi
.SH "Member Data Documentation"
.PP 
.SS "final Logger com\&.poly\&.nlp\&.filekommander\&.views\&.panels\&.PhraseOperationActionPanel\&.log = Logger\&.getLogger(PhraseOperationActionPanel\&.class)\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 32 of file PhraseOperationActionPanel\&.java\&.
.SS "\fBPhraseOperationModel\fP com\&.poly\&.nlp\&.filekommander\&.views\&.panels\&.PhraseOperationActionPanel\&.model\fC [private]\fP"

.PP
Definition at line 31 of file PhraseOperationActionPanel\&.java\&.
.SS "final long com\&.poly\&.nlp\&.filekommander\&.views\&.panels\&.PhraseOperationActionPanel\&.serialVersionUID = 1L\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 28 of file PhraseOperationActionPanel\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FileKommander from the source code\&.
