.TH "com.poly.nlp.filekommander.FileKommanderException" 3 "Thu Dec 20 2012" "Version 0.001" "FileKommander" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.poly.nlp.filekommander.FileKommanderException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits RuntimeException\&.
.SS "Package Functions"

.in +1c
.ti -1c
.RI "\fBFileKommanderException\fP (String message)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final long \fBserialVersionUID\fP = 1L"
.br
.ti -1c
.RI "static final Logger \fBlog\fP = Logger\&.getLogger(FileKommanderException\&.class)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
neha , jake 
.RE
.PP

.PP
Definition at line 13 of file FileKommanderException\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.poly\&.nlp\&.filekommander\&.FileKommanderException\&.FileKommanderException (Stringmessage)\fC [package]\fP"

.PP
Definition at line 22 of file FileKommanderException\&.java\&.
.PP
.nf
                                          {  
        log\&.error(message);
    }
.fi
.SH "Member Data Documentation"
.PP 
.SS "final Logger com\&.poly\&.nlp\&.filekommander\&.FileKommanderException\&.log = Logger\&.getLogger(FileKommanderException\&.class)\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 19 of file FileKommanderException\&.java\&.
.SS "final long com\&.poly\&.nlp\&.filekommander\&.FileKommanderException\&.serialVersionUID = 1L\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 18 of file FileKommanderException\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FileKommander from the source code\&.
