.TH "com.poly.nlp.filekommander.views.models.GenericActionModel" 3 "Thu Dec 20 2012" "Version 0.001" "FileKommander" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.poly.nlp.filekommander.views.models.GenericActionModel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBcom\&.poly\&.nlp\&.filekommander\&.views\&.models\&.CreateModel\fP, \fBcom\&.poly\&.nlp\&.filekommander\&.views\&.models\&.DeleteModel\fP, \fBcom\&.poly\&.nlp\&.filekommander\&.views\&.models\&.PhraseOperationModel\fP, \fBcom\&.poly\&.nlp\&.filekommander\&.views\&.models\&.RenameModel\fP, and \fBcom\&.poly\&.nlp\&.filekommander\&.views\&.models\&.StatsModel\fP\&.
.SH "Detailed Description"
.PP 
Definition at line 3 of file GenericActionModel\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FileKommander from the source code\&.
