.TH "git/FileKommander/src/com/poly/nlp/filekommander/views/FileKommanderGUI.java" 3 "Sat Dec 22 2012" "Version 0.001" "FileKommander" \" -*- nroff -*-
.ad l
.nh
.SH NAME
git/FileKommander/src/com/poly/nlp/filekommander/views/FileKommanderGUI.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcom\&.poly\&.nlp\&.filekommander\&.views\&.FileKommanderGUI\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBcom\&.poly\&.nlp\&.filekommander\&.views\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FileKommander from the source code\&.
