.TH "git/FileKommander/src/com/poly/nlp/filekommander/views/SwingLogAppender.java" 3 "Thu Dec 20 2012" "Version 0.001" "FileKommander" \" -*- nroff -*-
.ad l
.nh
.SH NAME
git/FileKommander/src/com/poly/nlp/filekommander/views/SwingLogAppender.java \- 
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for FileKommander from the source code\&.
